### ISSUE TITLE
Option to download previous versions of Ajax Search Pro in settings (or on the webpage)

### ISSUE THREAD

**Issue by exetico** [WPDreams/ajax-search-pro-development#144]
As I'm facing issues with the latest version of ASP, I've not managed to find a single place, where I can get a older version. I even checked the update endpoint with Postman, but I'm not able to pick up any query select to be provided, in order to get another version (I know, I dit step an extra step, there).

I also checked codecanyon, but it does not look like they offer a way to fetch a older version.

So here, I'm stuck with a broken version; **If** there is a way to do it, kindly add it to the docs, and add some keywords like "downgrad" "previous" "recovery" "emergency" or similar words.

In the end, I've temporary excluded the Ajax Search Pro script from our Javascript bundle, as I didn't want to spend time on restoring a full system backup with 100GB of data+, even though it's cloud managed.

Are there a function for this already? If so, I've missed it.

Let us get some kind of solution, where we're able to pick up another version of Ajax Search Pro.

**Comment by ernestmarcinko** [comment]
It is not possible to downgrade, that may cause more issues.

What seems to be the problem? Is it the script minification? Please check [this reply](https://github.com/wpdreams/ajax-search-pro-development/issues/143#issuecomment-2265302400), you can either exclude the files from the additional minify step or change the default source to non-minified.

**Comment by exetico** [comment]
If you expect it will be a problem in some cases, I get that. But as a user, upgrading the version, with just a single "path" version bump, wouldn't be expected as things would break. In that case, I'd personally be very happy with a way of knowing that I'm able to take a step back hereafter, downgrading the the previous patch-version (if [senmatic versionening](https://semver.org/) are followed, that would also indicate if I, as a user, needs to pay extra attention to the changelog).

For the discussion related to the asp-script, I've added my input in #143.

**Comment by ernestmarcinko** [comment]
Just to add more context to this - it's also forbidden by our vendor to provide anything but the latest release.

Path version update made sense, as beta testing did not reveal any issues and the source scripts were basically not changed. If you think about it, the scripts do work, it's the 3rd party minification that's breaking it. This is just a very unfortunate coincidence that nobody from beta nor us was testing against page minify plugins. Cache plugins always have a warning message when using minification that it may not work correctly - which this case just proved to be true.

Still I will try to accomodate these as much as I can, but I would be more happy if there was a way for page minifiers to  be more careful about breaking scripts and not leaving it up to the user. But my guess is that it may not be possible just because how confusing javascript syntax can be.

**Comment by exetico** [comment]
I fully get that it ended up in a release. That's not to be blamed, or anything like that. You've also taken your part now, and had things fixed **quickly**. So, all in all, things turned out great.

But I still hold my point about the versioning. There was clearly a risk involved, and switching builder-solution, resulting in another structure for the front-end script, should at least have been released with a MINOR versioning bump.

_Oh, btw, I'll give the beta a test in a few minutes._

Thank you for looking into this, and fast-follows up. That's much appreciated.
